"""Sprint 5 independent validation (s5-validation): GB 503 reliable saves.

- A simulated timeout (the server committed, the client never saw the answer and retries the same
  create + set) leaves the counts of sessions, sets, reps, form events and links unchanged.
- Concurrent duplicates never create duplicates or 500s.
- A conflicting replay (same clientSetId, different content) is 409 and changes nothing.
- Replays after finalization still answer 200; new sets are 409 `workout-finalized`.
- End to end: payloads built by the REAL frontend chain (tests/fixtures/frontend_set_payloads.json,
  generated by frontend/tests/fixtures/workout-payload-fixtures.js from SYNTHETIC frames) are accepted
  and every summary field round-trips through GET detail.
Runs against the real PostgreSQL test database (TEST_DATABASE_URL).
"""

from __future__ import annotations

import copy
import json
import threading
from concurrent.futures import ThreadPoolExecutor
from datetime import UTC, datetime, timedelta
from pathlib import Path
from zoneinfo import ZoneInfo

import pytest
from sqlalchemy import text

from tests.conftest import auth_header, iso, make_set_payload, register_user, workout_body

FIXTURES = json.loads((Path(__file__).parent / "fixtures" / "frontend_set_payloads.json").read_text())
COUNTED = ("workout_sessions", "workout_sets", "reps", "form_events", "form_event_reps")


def counts(engine) -> dict[str, int]:
    with engine.connect() as connection:
        return {t: connection.execute(text(f"SELECT count(*) FROM {t}")).scalar_one() for t in COUNTED}


@pytest.fixture
def headers(api):
    return auth_header(register_user(api)["accessToken"])


def save(api, headers, workout, payload):
    """What saveQueue.save does: idempotent create, then submit the set."""
    created = api.post("/api/workouts", json=workout, headers=headers)
    assert created.status_code in (200, 201), created.text
    submitted = api.post(f"/api/workouts/{created.json()['id']}/sets", json=payload, headers=headers)
    return created, submitted


# ---------------------------------------------------------------------------------------------
# Simulated timeout: committed on the server, retried by the client with the same ids and body.
# ---------------------------------------------------------------------------------------------

def test_retry_after_lost_response_changes_no_counts(api, headers, clean_db):
    workout = workout_body()
    payload = make_set_payload(1, 4, mode="review")
    created, submitted = save(api, headers, workout, payload)
    assert (created.status_code, submitted.status_code) == (201, 201)
    after_first = counts(clean_db)
    assert after_first == {"workout_sessions": 1, "workout_sets": 1, "reps": 4, "form_events": 3,
                           "form_event_reps": after_first["form_event_reps"]}
    assert after_first["form_event_reps"] > 0
    first_detail = api.get(f"/api/workouts/{created.json()['id']}", headers=headers).json()

    for _ in range(3):  # the client retries several times (each response "lost")
        again_created, again_submitted = save(api, headers, copy.deepcopy(workout), copy.deepcopy(payload))
        assert again_created.status_code == 200 and again_created.json()["id"] == created.json()["id"]
        assert again_submitted.status_code == 200
        assert again_submitted.json()["id"] == submitted.json()["id"]
        assert counts(clean_db) == after_first
    assert api.get(f"/api/workouts/{created.json()['id']}", headers=headers).json() == first_detail


def test_retry_while_first_request_still_in_flight(make_api, clean_db):
    """The client gives up (timeout) while the server is still working and retries; both requests then
    complete. Modelled by holding the workout row lock in another connection so the first request is
    stuck in the server, sending the retry, then releasing the lock."""
    api_slow, api_retry = make_api(), make_api()
    headers = auth_header(register_user(api_slow)["accessToken"])
    workout = api_slow.post("/api/workouts", json=workout_body(), headers=headers).json()
    payload = make_set_payload(1, 3, mode="review")
    url = f"/api/workouts/{workout['id']}/sets"
    with clean_db.connect() as blocker:
        tx = blocker.begin()
        blocker.execute(text("SELECT id FROM workout_sessions WHERE id = :id FOR UPDATE"), {"id": workout["id"]})
        with ThreadPoolExecutor(2) as pool:
            first = pool.submit(api_slow.post, url, json=payload, headers=headers)
            retry = pool.submit(api_retry.post, url, json=payload, headers=headers)
            threading.Event().wait(0.5)
            assert not first.done() and not retry.done(), "requests should be waiting on the row lock"
            tx.rollback()
            statuses = sorted([first.result(timeout=20).status_code, retry.result(timeout=20).status_code])
    assert statuses == [200, 201]
    c = counts(clean_db)
    assert (c["workout_sets"], c["reps"], c["form_events"]) == (1, 3, 3)


def test_replay_equivalent_encodings_are_identical(api, headers, clean_db):
    """A body re-serialized after a reload (different key order, +00:00 instead of Z) is the same save."""
    workout = workout_body()
    payload = make_set_payload(1, 3, mode="review")
    save(api, headers, workout, payload)
    before = counts(clean_db)
    reordered = json.loads(json.dumps(payload, sort_keys=True))
    reordered = {k: reordered[k] for k in reversed(list(reordered))}
    reordered["summary"] = {k: reordered["summary"][k] for k in reversed(list(reordered["summary"]))}
    reordered["endedAt"] = reordered["endedAt"].replace("Z", "+00:00")
    workout_offset = {**workout, "startedAt": datetime.fromisoformat(workout["startedAt"].replace("Z", "+00:00"))
                      .astimezone(ZoneInfo("America/Chicago")).isoformat()}
    created, submitted = save(api, headers, workout_offset, reordered)
    assert created.status_code == 200
    assert submitted.status_code == 200, submitted.text
    assert counts(clean_db) == before


def test_replay_with_cue_log_changed_is_still_identical(api, headers, clean_db):
    """cueLog is dropped before hashing, so a replay that carries a different cue log is a replay."""
    workout = workout_body()
    payload = make_set_payload(1, 2)
    save(api, headers, workout, payload)
    payload2 = copy.deepcopy(payload)
    payload2["summary"]["cueLog"] = []
    _, submitted = save(api, headers, workout, payload2)
    assert submitted.status_code == 200
    assert counts(clean_db)["workout_sets"] == 1


# ---------------------------------------------------------------------------------------------
# Concurrent duplicates
# ---------------------------------------------------------------------------------------------

def _parallel(n, fn):
    barrier = threading.Barrier(n)

    def run(i):
        barrier.wait()
        return fn(i)

    with ThreadPoolExecutor(n) as pool:
        return list(pool.map(run, range(n)))


def test_concurrent_duplicate_creates_and_sets(make_api, clean_db):
    clients = [make_api() for _ in range(6)]
    headers = auth_header(register_user(clients[0])["accessToken"])
    workout = workout_body()
    payload = make_set_payload(1, 5, mode="review")

    creates = _parallel(6, lambda i: clients[i].post("/api/workouts", json=workout, headers=headers))
    assert sorted(r.status_code for r in creates) == [200] * 5 + [201], [r.text for r in creates]
    assert len({r.json()["id"] for r in creates}) == 1
    wid = creates[0].json()["id"]

    sets = _parallel(6, lambda i: clients[i].post(f"/api/workouts/{wid}/sets", json=payload, headers=headers))
    assert sorted(r.status_code for r in sets) == [200] * 5 + [201], [r.text for r in sets]
    assert len({r.json()["id"] for r in sets}) == 1
    c = counts(clean_db)
    assert (c["workout_sessions"], c["workout_sets"], c["reps"], c["form_events"]) == (1, 1, 5, 3)


def test_concurrent_conflicting_sets_one_wins_rest_409(make_api, clean_db):
    clients = [make_api() for _ in range(4)]
    headers = auth_header(register_user(clients[0])["accessToken"])
    wid = clients[0].post("/api/workouts", json=workout_body(), headers=headers).json()["id"]
    base = make_set_payload(1, 2, client_set_id="set-race")
    variants = []
    for i in range(4):
        variant = copy.deepcopy(base)
        variant["summary"]["sessionId"] = f"variant-{i}"
        variants.append(variant)
    results = _parallel(4, lambda i: clients[i].post(f"/api/workouts/{wid}/sets", json=variants[i], headers=headers))
    statuses = sorted(r.status_code for r in results)
    assert statuses == [201, 409, 409, 409], [r.text for r in results]
    assert all(r.json()["detail"]["code"] == "conflict" for r in results if r.status_code == 409)
    assert counts(clean_db)["workout_sets"] == 1 and counts(clean_db)["reps"] == 2


def test_concurrent_different_sets_same_index_one_wins(make_api, clean_db):
    clients = [make_api() for _ in range(3)]
    headers = auth_header(register_user(clients[0])["accessToken"])
    wid = clients[0].post("/api/workouts", json=workout_body(), headers=headers).json()["id"]
    payloads = [make_set_payload(1, 2) for _ in range(3)]  # different clientSetIds, same setIndex
    results = _parallel(3, lambda i: clients[i].post(f"/api/workouts/{wid}/sets", json=payloads[i], headers=headers))
    assert sorted(r.status_code for r in results) == [201, 409, 409], [r.text for r in results]
    assert counts(clean_db)["workout_sets"] == 1


# ---------------------------------------------------------------------------------------------
# Conflicting replays and finalization
# ---------------------------------------------------------------------------------------------

@pytest.mark.parametrize("change", [
    lambda p: p["reps"][0].update(romDeg=p["reps"][0]["romDeg"] + 1),
    lambda p: p.update(endedAt=iso(datetime.fromisoformat(p["endedAt"].replace("Z", "+00:00")) + timedelta(seconds=1))),
    lambda p: p["summary"].update(featureVersion="9.9.9"),
    lambda p: (p["formEvents"][0].update(peak=99.0), p["summary"]["episodes"][0].update(peak=99.0)),
])
def test_conflicting_replay_is_409_and_changes_nothing(api, headers, clean_db, change):
    workout = workout_body()
    payload = make_set_payload(1, 3, mode="review")
    created, _ = save(api, headers, workout, payload)
    detail = api.get(f"/api/workouts/{created.json()['id']}", headers=headers).json()
    before = counts(clean_db)
    altered = copy.deepcopy(payload)
    change(altered)
    _, submitted = save(api, headers, workout, altered)
    assert submitted.status_code == 409
    assert submitted.json()["detail"]["code"] == "conflict"
    assert counts(clean_db) == before
    assert api.get(f"/api/workouts/{created.json()['id']}", headers=headers).json() == detail


def test_conflicting_workout_create_is_409(api, headers, clean_db):
    workout = workout_body()
    save(api, headers, workout, make_set_payload(1, 1))
    other = {**workout, "startedAt": iso(datetime.now(UTC) - timedelta(hours=5))}
    response = api.post("/api/workouts", json=other, headers=headers)
    assert response.status_code == 409 and response.json()["detail"]["code"] == "conflict"
    assert counts(clean_db)["workout_sessions"] == 1


def test_replay_after_finalize(api, headers, clean_db):
    workout = workout_body()
    payload = make_set_payload(1, 3, mode="review")
    created, submitted = save(api, headers, workout, payload)
    wid = created.json()["id"]
    final = api.post(f"/api/workouts/{wid}/finalize", json={"endedAt": iso(datetime.now(UTC))}, headers=headers)
    assert final.status_code == 200 and final.json()["status"] == "finalized"
    before = counts(clean_db)

    # The queue retries create + set (e.g. its finalize response was lost): both are accepted replays.
    again_created, again_submitted = save(api, headers, workout, payload)
    assert again_created.status_code == 200 and again_created.json()["status"] == "finalized"
    assert again_submitted.status_code == 200 and again_submitted.json()["id"] == submitted.json()["id"]
    # A repeated finalize (even with another endedAt) returns the stored state unchanged.
    repeat = api.post(f"/api/workouts/{wid}/finalize", json={"endedAt": iso(datetime.now(UTC) - timedelta(seconds=5))},
                      headers=headers)
    assert repeat.status_code == 200 and repeat.json() == final.json()
    # A new set, or a conflicting replay, is refused.
    new_set = api.post(f"/api/workouts/{wid}/sets", json=make_set_payload(2, 1), headers=headers)
    assert new_set.status_code == 409 and new_set.json()["detail"]["code"] == "workout-finalized"
    altered = copy.deepcopy(payload)
    altered["reps"][0]["romDeg"] += 1
    conflict = api.post(f"/api/workouts/{wid}/sets", json=altered, headers=headers)
    assert conflict.status_code == 409 and conflict.json()["detail"]["code"] == "conflict"
    assert counts(clean_db) == before


# ---------------------------------------------------------------------------------------------
# End to end: payloads from the real frontend builder
# ---------------------------------------------------------------------------------------------

def _workout_for(payload: dict) -> dict:
    return workout_body(started_at=datetime.fromisoformat(payload["startedAt"].replace("Z", "+00:00")))


def _close(a, b) -> bool:
    if isinstance(a, float) or isinstance(b, float):
        return a is not None and b is not None and abs(a - b) < 1e-9
    return a == b


@pytest.mark.parametrize("name", ["validatedOnly", "review"])
def test_frontend_built_payload_round_trips_every_field(api, headers, clean_db, name):
    payload = copy.deepcopy(FIXTURES[name])
    workout = _workout_for(payload)
    created, submitted = save(api, headers, workout, payload)
    assert submitted.status_code == 201, submitted.text
    detail = api.get(f"/api/workouts/{created.json()['id']}", headers=headers).json()
    stored = detail["sets"][0]
    summary = payload["summary"]

    assert "cueLog" not in summary  # the builder already drops it
    assert stored["summary"] == summary, "stored summary differs from the sent summary"
    columns = {
        "clientSetId": payload["clientSetId"], "setIndex": payload["setIndex"], "side": summary["side"],
        "view": summary["view"], "mode": summary["mode"], "summarySchemaVersion": summary["schemaVersion"],
        "analyzerVersion": summary["analyzerVersion"], "featureVersion": summary["featureVersion"],
        "rulesVersion": summary["rulesVersion"], "feedbackVersion": summary["feedbackVersion"],
        "completedReps": summary["completedReps"], "analyzedReps": summary["analyzedReps"],
        "issueBearingReps": summary["issueBearingReps"], "noIssueReps": summary["noIssueReps"],
        "noIssueFraction": summary["noIssueFraction"], "notAnalyzedReason": summary["notAnalyzedReason"],
        "trackingAssessableMs": summary["trackingCoverage"]["assessableMs"],
        "trackingSessionMs": summary["trackingCoverage"]["sessionMs"],
        "trackingCoverage": summary["trackingCoverage"]["fraction"],
        "interruptedAttempts": summary["interruptedAttempts"], "episodeCountsByType": summary["episodeCountsByType"],
    }
    for key, expected in columns.items():
        assert _close(stored[key], expected), (key, stored[key], expected)
    for key in ("startedAt", "endedAt"):
        assert datetime.fromisoformat(stored[key]) == datetime.fromisoformat(payload[key].replace("Z", "+00:00"))
        assert datetime.fromisoformat(stored[key]).utcoffset() == timedelta(0), "stored times must come back as UTC"

    assert [r["clientRepId"] for r in stored["reps"]] == [r["clientRepId"] for r in payload["reps"]]
    for sent, got in zip(payload["reps"], stored["reps"], strict=True):
        for key, value in sent.items():
            assert _close(got[key], value), (key, got[key], value)
    sent_events = {e["clientEventId"]: e for e in payload["formEvents"]}
    assert set(sent_events) == {e["clientEventId"] for e in stored["formEvents"]}
    for got in stored["formEvents"]:
        for key, value in sent_events[got["clientEventId"]].items():
            assert _close(got[key], value), (key, got[key], value)
    # Totals are derived from the stored rows.
    assert detail["totals"] == {"sets": 1, "completedReps": summary["completedReps"],
                                "analyzedReps": summary["analyzedReps"], "issueBearingReps": summary["issueBearingReps"]}
    # And the identical replay is accepted.
    again, replay = save(api, headers, workout, copy.deepcopy(FIXTURES[name]))
    assert (again.status_code, replay.status_code) == (200, 200)
    assert counts(clean_db)["workout_sets"] == 1


def test_frontend_review_payload_links_events_to_reps(api, headers, clean_db):
    payload = copy.deepcopy(FIXTURES["review"])
    save(api, headers, _workout_for(payload), payload)
    assert counts(clean_db)["form_event_reps"] == sum(len(e["repClientIds"]) for e in payload["formEvents"]) > 0


def test_frontend_payload_no_frames_is_rejected_and_leaves_empty_workout(api, headers, clean_db):
    """Finish before any tracked frame: side, view and featureVersion are null in the summary.

    Observed behaviour (reported to the lead): the set is 422 (not retryable), but the workout created
    first by the save queue stays behind as an open workout with 0 sets in the history list.
    """
    payload = copy.deepcopy(FIXTURES["noFrames"])
    assert payload["summary"]["side"] is None and payload["summary"]["view"] is None
    created, submitted = save(api, headers, _workout_for(payload), payload)
    assert submitted.status_code == 422
    body = submitted.text
    for field in ("side", "view", "featureVersion"):
        assert field in body, f"422 should name summary.{field}"
    assert counts(clean_db)["workout_sets"] == 0
    items = api.get("/api/workouts", headers=headers).json()["items"]
    assert [(i["id"], i["totals"]["sets"]) for i in items] == [(created.json()["id"], 0)]
