"""GB 502: Alembic `0001_initial` on an empty database, downgrade, re-upgrade, and no model drift."""

from __future__ import annotations

import pytest
from alembic import command
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import create_engine, inspect, text
from sqlalchemy.pool import NullPool

from tests.conftest import TEST_DATABASE_URL, alembic_config, reset_schema

TABLES = {"users", "auth_sessions", "exercises", "workout_sessions", "workout_sets", "reps", "form_events",
          "form_event_reps"}


def snapshot():
    engine = create_engine(TEST_DATABASE_URL, poolclass=NullPool)
    try:
        with engine.connect() as connection:
            tables = set(inspect(connection).get_table_names())
            version = connection.execute(text("SELECT version_num FROM alembic_version")).scalar() \
                if "alembic_version" in tables else None
            exercises = connection.execute(text(
                "SELECT id, name, supported_views, analyzer_version, active FROM exercises")).all() \
                if "exercises" in tables else None
            checks = connection.execute(text(
                "SELECT conname FROM pg_constraint WHERE contype = 'c' AND connamespace = 'public'::regnamespace"
            )).scalars().all()
        return tables, version, exercises, set(checks)
    finally:
        engine.dispose()


@pytest.fixture
def isolated_schema(db_engine):
    """Rebuild the shared test schema around this test and leave it at head for the others."""
    db_engine.dispose()
    reset_schema()
    yield alembic_config()
    db_engine.dispose()
    reset_schema()
    command.upgrade(alembic_config(), "head")


def test_upgrade_downgrade_upgrade_and_no_drift(isolated_schema):
    config = isolated_schema
    command.upgrade(config, "head")
    tables, version, exercises, checks = snapshot()
    assert TABLES <= tables
    assert version == "0001_initial"
    assert [tuple(row) for row in exercises] == [("dumbbell-curl", "Dumbbell curl", ["side"], "curl-1.1.0", True)]
    for name in ("ck_users_email_lower_case", "ck_workout_sessions_status_allowed",
                 "ck_workout_sets_no_issue_consistent", "ck_workout_sets_analyzed_le_completed",
                 "ck_workout_sets_issue_bearing_le_analyzed", "ck_reps_end_after_start"):
        assert name in checks

    command.downgrade(config, "base")
    tables, version, _, _ = snapshot()
    assert tables & TABLES == set()
    assert version is None

    command.upgrade(config, "head")
    command.check(config)  # raises AutogenerateDiffsDetected if models and migration differ


def test_check_detects_drift(isolated_schema):
    """Guard that `alembic check` really compares: a schema changed outside Alembic must be reported."""
    command.upgrade(isolated_schema, "head")
    engine = create_engine(TEST_DATABASE_URL, poolclass=NullPool)
    try:
        with engine.begin() as connection:
            connection.execute(text("DROP INDEX ix_workout_sessions_user_id_started_at"))
    finally:
        engine.dispose()
    with pytest.raises(AutogenerateDiffsDetected):
        command.check(isolated_schema)


def test_constraints_enforced_by_database(isolated_schema):
    command.upgrade(isolated_schema, "head")
    engine = create_engine(TEST_DATABASE_URL, poolclass=NullPool)
    try:
        with pytest.raises(Exception) as caught, engine.begin() as connection:
            connection.execute(text("INSERT INTO users (id, email, password_hash) VALUES (gen_random_uuid(), 'UP@x.com', 'h')"))
        assert "ck_users_email_lower_case" in str(caught.value)
    finally:
        engine.dispose()
